Removed memory retain cycle for block
e-Sixt/Swen pull request #9
Opened 2017-07-17 09:21 UTC by bhabani-sixt

Block, copy to heap and create memory retain cycle. Added weak to break retain cycle chain.

2017-07-17 10:58 UTC, kimlanbui commented on Swen/Classes/Swen.swift
> +            listener.queue.addOperation {[weak listener] in
there is a missing space between { and [

2017-07-17 10:59 UTC, kimlanbui commented on Swen/Classes/Swen.swift
> +            queue.addOperation {[weak self] in
there is a missing space between { and [

2017-07-18 17:41 UTC, dmitryPoznukhov requested changes

2017-07-18 17:41 UTC, dmitryPoznukhov commented on Example/Tests/SwenTests.swift
> +    func testReleaseListeners() {
actually I think, it's enough to have:

   ```
 func testReleaseListeners() {
        Swen.post(TestStickyEvent())

        Swen<TestStickyEvent>.register(self) { _ in }
        weak var listener = Swen<TestStickyEvent>.instance(in: .defaultStorage).listeners.first
        Swen<TestStickyEvent>.unregister(self)

        XCTAssertNil(listener)
    }
```

2017-07-18 17:41 UTC, dmitryPoznukhov commented on Swen/Classes/Swen.swift
> -            queue.addOperation {
please, add test, to show that this changes is necessary

2017-07-19 07:13 UTC, bhabani-sixt commented on Example/Tests/SwenTests.swift
> +    func testReleaseListeners() {
+1

2017-07-19 11:45 UTC, bhabani-sixt commented on Swen/Classes/Swen.swift
> -            queue.addOperation {
Added new test cases.

2017-07-19 12:30 UTC, dmitryPoznukhov requested changes

2017-07-19 12:30 UTC, dmitryPoznukhov commented on Example/Tests/SwenTests.swift
> +    func testReleaseListenersForStickyEvent() {
you can do it in this way as well:

```
    func testReleaseListenersForNonStickyEvent() {
        let registerQueue = OperationQueue()

        Swen<TestEvent>.register(self, onQueue: registerQueue) { _ in }
        weak var listener = Swen<TestEvent>.instance(in: .defaultStorage).listeners.first
        Swen.post(TestEvent())
        Swen<TestEvent>.unregister(self)

        XCTAssertNil(listener)
    }
```

2017-07-19 13:10 UTC, dmitryPoznukhov approved these changes

2017-07-19 13:37 UTC, merged